/* ********** REDUX/REDUCERS BEGIN ********** */
export const LOGIN_POST_START = "LOGIN_POST_START";
export const LOGIN_POST_SUCCESS = "LOGIN_POST_SUCCESS";
export const LOGIN_POST_FAILURE = "LOGIN_POST_FAILURE";

export const LOGOUT = "LOGOUT";

export const SIGNUP_POST_START = "SIGNUP_POST_START";
export const SIGNUP_POST_SUCCESS = "SIGNUP_POST_SUCCESS";
export const SIGNUP_POST_FAILURE = "SIGNUP_POST_FAILURE";

export const PROJECTS_LOAD_START = "PROJECTS_LOAD_START";
export const PROJECTS_LOAD_SUCCESS = "PROJECTS_LOAD_SUCCESS";
export const PROJECTS_LOAD_FAILURE = "PROJECTS_LOAD_FAILURE";

export const PROJECTS_POST_START = "PROJECTS_POST_START";
export const PROJECTS_POST_SUCCESS = "PROJECTS_POST_SUCCESS";
export const PROJECTS_POST_FAILURE = "PROJECTS_POST_FAILURE";

export const PROJECTS_PUT_START = "PROJECTS_PUT_START";
export const PROJECTS_PUT_SUCCESS = "PROJECTS_PUT_SUCCESS";
export const PROJECTS_PUT_FAILURE = "PROJECTS_PUT_FAILURE";

export const PROJECTS_DELETE_START = "PROJECTS_DELETE_START";
export const PROJECTS_DELETE_SUCCESS = "PROJECTS_DELETE_SUCCESS";
export const PROJECTS_DELETE_FAILURE = "PROJECTS_DELETE_FAILURE";

export const TASKS_LOAD_START = "TASKS_LOAD_START";
export const TASKS_LOAD_SUCCESS = "TASKS_LOAD_SUCCESS";
export const TASKS_LOAD_FAILURE = "TASKS_LOAD_FAILURE";

export const TASKS_POST_START = "TASKS_POST_START";
export const TASKS_POST_SUCCESS = "TASKS_POST_SUCCESS";
export const TASKS_POST_FAILURE = "TASKS_POST_FAILURE";

export const TASKS_PUT_START = "TASKS_PUT_START";
export const TASKS_PUT_SUCCESS = "TASKS_PUT_SUCCESS";
export const TASKS_PUT_FAILURE = "TASKS_PUT_FAILURE";

export const TASKS_DELETE_START = "TASKS_DELETE_START";
export const TASKS_DELETE_SUCCESS = "TASKS_DELETE_SUCCESS";
export const TASKS_DELETE_FAILURE = "TASKS_DELETE_FAILURE";

export const USER_VALUES_LOAD_START = "USER_VALUES_LOAD_START";
export const USER_VALUES_LOAD_SUCCESS = "USER_VALUES_LOAD_SUCCESS";
export const USER_VALUES_LOAD_FAILURE = "USER_VALUES_LOAD_FAILURE";

export const USER_VALUES_POST_START = "USER_VALUES_POST_START";
export const USER_VALUES_POST_SUCCESS = "USER_VALUES_POST_SUCCESS";
export const USER_VALUES_POST_FAILURE = "USER_VALUES_POST_FAILURE";

export const USER_VALUES_PUT_START = "USER_VALUES_PUT_START";
export const USER_VALUES_PUT_SUCCESS = "USER_VALUES_PUT_SUCCESS";
export const USER_VALUES_PUT_FAILURE = "USER_VALUES_PUT_FAILURE";

export const USER_VALUES_DELETE_START = "USER_VALUES_DELETE_START";
export const USER_VALUES_DELETE_SUCCESS = "USER_VALUES_DELETE_SUCCESS";
export const USER_VALUES_DELETE_FAILURE = "USER_VALUES_DELETE_FAILURE";

export const REMOVE_VALUE = "REMOVE_VALUE";
export const TOGGLE_VALUE = "TOGGLE_VALUE";

export const ADD_TO_TOP_TEMP_LIST = "ADD_TO_TOP_TEMP_LIST";
export const REMOVE_FROM_TOP_TEMP_LIST = "REMOVE_FROM_TOP_TEMP_LIST";

export const USER_GET_START = "USER_GET_START";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAILURE = "USER_GET_FAILURE";

export const USER_POST_START = "USER_POST_START";
export const USER_POST_SUCCESS = "USER_POST_SUCCESS";
export const USER_POST_FAILURE = "USER_POST_FAILURE";

export const USER_PUT_START = "USER_PUT_START";
export const USER_PUT_SUCCESS = "USER_PUT_SUCCESS";
export const USER_PUT_FAILURE = "USER_PUT_FAILURE";

export const USER_DELETE_START = "USER_DELETE_START";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";

export const VALUES_LOAD_START = "VALUES_LOAD_START";
export const VALUES_LOAD_SUCCESS = "VALUES_LOAD_SUCCESS";
export const VALUES_LOAD_FAILURE = "VALUES_LOAD_FAILURE";

export const VALUES_POST_START = "VALUES_POST_START";
export const VALUES_POST_SUCCESS = "VALUES_POST_SUCCESS";
export const VALUES_POST_FAILURE = "VALUES_POST_FAILURE";

export const VALUES_PUT_START = "VALUES_PUT_START";
export const VALUES_PUT_SUCCESS = "VALUES_PUT_SUCCESS";
export const VALUES_PUT_FAILURE = "VALUES_PUT_FAILURE";

export const VALUES_DELETE_START = "VALUES_DELETE_START";
export const VALUES_DELETE_SUCCESS = "VALUES_DELETE_SUCCESS";
export const VALUES_DELETE_FAILURE = "VALUES_DELETE_FAILURE";

export const ZEN_LOAD_START = "ZEN_LOAD_START";
export const ZEN_LOAD_SUCCESS = "ZEN_LOAD_SUCCESS";
export const ZEN_LOAD_FAILURE = "ZEN_LOAD_FAILURE";
/* ********** REDUX/REDUCERS END ********** */

/* ********** MODALS BEGIN ********** */
export const LOGIN_MODAL_OPEN = "LOGIN_MODAL_OPEN";
export const LOGIN_MODAL_CLOSE = "LOGIN_MODAL_CLOSE";

export const SIGNUP_MODAL_OPEN = "SIGNUP_MODAL_OPEN";
export const SIGNUP_MODAL_CLOSE = "SIGNUP_MODAL_CLOSE";
/* ********** MODALS END ********** */
